### ISSUE TITLE
Example question not working for me.

### ISSUE THREAD

**Issue by labapen** [jsxgraph/moodleformulas_jsxgraph#5]
Hello,
I want to use jsxgraph with my formulas type questions using jsxgraph filter. I have installed Moodle on my computer and everything works fine. I tried the example shown here but when I hit preview, I only see the code (from <jsxgraph...> to </jsxgraph>. I set the plain text editor everywhere (both editor preferences and manage editors). The filter works fine when I try it on content like a page or a label though.
Can you please help me figure out what I did wrong? I watched the videos on youtube and even went on moodle.itemspro.eu, but unfortunately, they did not show how to write a complete question step by step from scratch, but rather how to edit an existing one. I thought the example here would be a good start. I don't know anything about coding and all, but I can follow the instructions on how to get something done (I have installed moodle on my own :-) )
Thank you for your help.

**Comment by andreas-web** [comment]
Dear labapen!

To help you, I have a few questions for you:
1. Did you also install the JSXGraph filter(https://moodle.org/plugins/filter_jsxgraph)?
2. Is this activated in the administrator interface? (Site administration > Plugins > Plugins overview)
3. Which Moodle version do you use?
4. Could you possibly export the question as Moodle XML and send it here? (Your course > Question bank)
Maybe some screenshots would help too...

Best regards,
Andreas

**Comment by labapen** [comment]
Dear Andreas!

Thank you for your quick reply. 
Strangely, everything works fine this morning. I don't know exactly what happened, but I am happy. 
Thanks to the team for this plugin!

Best regards,

**Comment by andreas-web** [comment]
Wonderful! If you still have problems, just re-open this issue.
