### ISSUE TITLE
TinyMCE is formatting Part 1 text...

### ISSUE THREAD

**Issue by idleup** [jsxgraph/moodleformulas_jsxgraph#8]
When I paste the code (from <jsxgraph...>) to the "Part 1" -> "Part's text" field and save the question the preview prints the code literally instead of executing it as HTML... Is there a way to change this field so the TinyMCE editor does not bind to it (like the variables fields) without removing TinyMCE as the field editor in the user preferences?

**Comment by andreas-web** [comment]
Dear Matt,

the reformatting of TinyMCE is a problem that comes up again and again. Unfortunately, we have not yet received a solution for this. Our filter only takes effect after the input has been finished and tthe content has been saved. TinyMCE may have already made changes here and there is nothing more we can do anymore.
In general, you are welcome to ask [Formulas developer team](https://github.com/FormulasQuestion/moodle-qtype_formulas) directly. Perhaps they have a solution.

Best regards,
Andreas
